clusterName: "opensearch-cluster"
nodeGroup: "master"
singleNode: false
masterService: "opensearch-cluster-master"
replicas: 3
roles:
  - master
  - ingest
  - data

extraEnvs:
  - name: OPENSEARCH_INITIAL_ADMIN_PASSWORD
    value: "YourStrongPassword123!"

persistence:
  enabled: false
extraVolumes:
  - name: opensearch-data
    hostPath:
      path: /mnt/opensearch-graylog
      type: DirectoryOrCreate
extraVolumeMounts:
  - name: opensearch-data
    mountPath: /usr/share/opensearch/data

antiAffinity: "soft"
antiAffinityTopologyKey: "kubernetes.io/hostname"

config:
  opensearch.yml: |
    cluster.name: opensearch-cluster
    network.host: 0.0.0.0
    discovery.seed_hosts: "opensearch-cluster-master-headless"
    cluster.initial_master_nodes: "opensearch-cluster-master-0,opensearch-cluster-master-1,opensearch-cluster-master-2"

resources:
  requests:
    cpu: "300m"
    memory: "1Gi"
  limits:
    memory: "1Gi"
opensearchJavaOpts: "-Xmx512m -Xms512m"
