name: Build and Push Docker Images

on:
  push:
    branches-ignore:
      - main

jobs:
  build-scan-remediate-push:
    name: Build and Push Docker Images for Each Branch
    runs-on: ubuntu-latest

    env:
      DOCKER_REPO: ${{ vars.CONTAINER_IMAGE }}
      GITHUB_REF_NAME: ${{ github.ref_name }}   

    steps:
      - name: 🛠️ Checkout Repository
        uses: actions/checkout@v4

      - name: 🔍 Verify Directory for Branch
        run: |
          if [ ! -d "./${GITHUB_REF_NAME}" ]; then
            echo "Directory ./${GITHUB_REF_NAME} does not exist for branch ${GITHUB_REF_NAME}."
            exit 1
          fi

      - name: 🐳 Build Docker Image
        working-directory: ./${GITHUB_REF_NAME}
        run: |
          docker build -t $DOCKER_REPO:${GITHUB_REF_NAME} .

      - name: 🚀 Push Docker Image
        working-directory: ./${GITHUB_REF_NAME}
        run: |
          echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USER }}" --password-stdin
          docker push $DOCKER_REPO:${GITHUB_REF_NAME}
