name: Build and Push Docker Images

on:
  pull_request:
    branches:
      - slurmctld
      - slurmdbd
      - slurmrestd
      
jobs:
  build-scan-remediate-push:
    name: Build and Push Docker Images for Each Branch
    runs-on: ubuntu-latest

    env:
      DOCKER_REPO: ${{ vars.CONTAINER_IMAGE }}
      GITHUB_REF_NAME: ${{ github.ref_name }}   

    steps:
      - name: 🛠️ Checkout Repository
        uses: actions/checkout@v4

      - name: 🐳 Build Docker Image
        run: |
          cd ${GITHUB_REF_NAME}
          docker build -t $DOCKER_REPO:${GITHUB_REF_NAME} .

      - name: 🚀 Push Docker Image
        run: |
          cd ${GITHUB_REF_NAME}      
          echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USER }}" --password-stdin
          docker push $DOCKER_REPO:${GITHUB_REF_NAME}
